[versions]
agp = "8.2.0-alpha14"
apache-pdfbox = "2.0.27"
constraintlayout-compose = "1.1.0-alpha11"
github-android-pdf-viewer = "3.2.0-beta.1"
github-pdfbox-android = "1.8.16.0"
gradle = "8.2.0-alpha14"
itextg = "5.5.10"
kotlin = "1.8.10"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
lifecycle-runtime-ktx = "2.6.1"
activity-compose = "1.7.2"
compose-bom = "2023.06.01"
material3 = "1.1.1"
navigation-compose = "2.7.0-beta02"
org-apache-pdfbox-pdfbox = "2.0.34"
retrofit = "2.9.0"
converter-gson = "2.9.0"
runtime-livedata = "1.6.0-alpha01"
lifecycle-viewmodel-compose = "2.6.1"
ui = "1.4.3"
tess-two = "9.1.0"
tess4j = "5.7.0"
pdfbox-tools = "3.0.0-RC1"
play-services-vision = "20.1.3"
room-compiler = "2.6.0-alpha02"
room-runtime = "2.6.0-alpha02"
preference-ktx = "1.2.0"
androidx-core-ktx = "1.12.0-alpha05"

[libraries]
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "ui" }
androidx-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "ui" }
androidx-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }
barteksc-android-pdf-viewer = { module = "com.github.barteksc:android-pdf-viewer", version.ref = "github-android-pdf-viewer" }
ben-eggers-pdfbox-android = { module = "io.github.ben-eggers:pdfbox-android", version.ref = "github-pdfbox-android" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
itextg = { module = "com.itextpdf:itextg", version.ref = "itextg" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
org-apache-pdfbox-pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "org-apache-pdfbox-pdfbox" }
pdfbox-layout = { module = "org.apache.pdfbox:pdfbox-layout", version.ref = "org-apache-pdfbox-pdfbox" }
pdfbox-v2027 = { module = "org.apache.pdfbox:pdfbox", version.ref = "apache-pdfbox" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { group = "androidx.compose.material3", name = "material3" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converter-gson" }
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtime-livedata" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
tess-two = { group = "com.rmtheis", name = "tess-two", version.ref = "tess-two" }
tess4j = { group = "net.sourceforge.tess4j", name = "tess4j", version.ref = "tess4j" }
pdfbox-tools = { group = "org.apache.pdfbox", name = "pdfbox-tools", version.ref = "pdfbox-tools" }
play-services-vision = { group = "com.google.android.gms", name = "play-services-vision", version.ref = "play-services-vision" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room-compiler" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room-runtime" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference-ktx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

